# Form implementation generated from reading ui file 'designed.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 874)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PreviousFolder = QtWidgets.QToolButton(self.centralwidget)
        self.PreviousFolder.setObjectName("PreviousFolder")
        self.horizontalLayout.addWidget(self.PreviousFolder)
        self.NextFolder = QtWidgets.QToolButton(self.centralwidget)
        self.NextFolder.setObjectName("NextFolder")
        self.horizontalLayout.addWidget(self.NextFolder)
        self.SearchLine = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchLine.setObjectName("SearchLine")
        self.horizontalLayout.addWidget(self.SearchLine)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.FoldersMenu = QtWidgets.QScrollArea(self.centralwidget)
        self.FoldersMenu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.FoldersMenu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.FoldersMenu.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.FoldersMenu.setWidgetResizable(True)
        self.FoldersMenu.setObjectName("FoldersMenu")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1113, 763))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FoldersMenu.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.FoldersMenu)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PreviousFolder.setText(_translate("MainWindow", "..."))
        self.NextFolder.setText(_translate("MainWindow", "..."))
